name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add conda to $PATH
      run: echo ::add-path::$CONDA/condabin

    - name: Update conda
      run: conda update -y -n base conda setuptools

    - name: Init conda
      run: |
        conda init bash
        conda info -a
    - name: Create the conda environment
      run: |
        conda create -n jupyterlab-module-federation --yes --quiet -c conda-forge nodejs jupyterlab
      env:
        PYTHON_VERSION: '3.8'

    - name: Build and install
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate jupyterlab-module-federation
        jlpm && jlpm run build

    - name: Browser check
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate jupyterlab-module-federation
        pip install jupyterlab==2.1.5
        python run.py

